config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories, only: [:index, :new, :create] do
    resources :expenses, only: [:new, :create, :index]
  end

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  include ImageUploader::Attachment(:icon)

  # Validation
  validates :name, presence: true

  # Associations
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses, dependent: :destroy

  def format_date(time_with_zone)
    time_with_zone.strftime('%d %b %Y')
  end
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  # Validation
  validates :expense, uniqueness: { scope: :category, message: 'already exists in this category' }

  # Associations
  belongs_to :expense
  belongs_to :category
end

app/models/expense.rb
class Expense < ApplicationRecord
  # Validations
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # Associations
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses, dependent: :destroy

  def format_date(time_with_zone)
    time_with_zone.strftime('%d %b %Y')
  end
end

app/models/expenses.rb
class Expense < ApplicationRecord
  # Validations
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # Associations
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses, dependent: :destroy

  def format_date(time_with_zone)
    time_with_zone.strftime('%d %b %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true
  validates :email, presence: true

  # Associations
  has_many :categories, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # to whitelist additional input fields other than what devise has by default
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_category, only: [:show]

  def index
    @categs = Category.all.order(created_at: :desc).includes(:expenses)
  end

  def new
    @new_category = Category.new
  end

  def create
    @category = Category.new(author_id: current_user.id, **category_params)

    if @category.save
      flash[:notice] = 'Category added successfully'
      redirect_to categories_path
    else
      flash.now[:alert] = 'Category could not be saved!'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[index create new]

  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order(created_at: :desc)
    @expenses_sum = @expenses.sum(:amount)
  end

  def new
    @new_expense = Expense.new
    @categories = Category.all
  end

  def create
    @expense = Expense.new(author_id: current_user.id, **expense_params)

    if @expense.save
      CategoryExpense.create!(category_id: @category.id, expense_id: @expense.id)
      flash[:notice] = 'Transaction recorded successfully'
      redirect_to category_expenses_path(@category)
    else
      flash.now[:alert] = 'Transaction could not be saved'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end

  def set_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::NumberHelper
end

app/views/categories/index.html.erb
<nav>
  <i class="material-icons md-36">menu</i>
  <h2>CATEGORIES</h2>
  <i class="material-icons md-36">search</i>
</nav>

<div class="container">
  <%= render 'shared/notification_box' %>

  <div>
    <% if @categs.empty? %>
      <p></p>
    <% else %>
      <% @categs.each_with_index do |categ, i| %>
        <div class='category-item'>
          <a href="/categories/<%= categ.id %>/expenses" class="category-item-row">
            <div class="img-container">
              <%= image_tag(categ.icon_url) if categ.icon %>
            </div>

            <div class="name-date-col">
              <h3><%= categ.name %></h3>
              <p><%= categ.format_date(categ.created_at) %></p>
            </div>

            <div class="amount-col">
              <h3><small><%= "$" + number_with_delimiter(categ.expenses.sum(:amount), delimiter: ',') + "0" %></small></h3>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>

    <div class="footer">
      <%= link_to "ADD CATEGORY", new_category_path, class: "add-cat-btn", role: "button" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<nav>
  <%= link_to "/categories" do %>
    <i class="material-icons md-36">arrow_back</i>
  <% end %>
  <h2>ADD CATEGORY</h2>
  <i class="material-icons md-36">search</i>
</nav>

<div class="container">
  <%= render 'shared/notification_box' %>

  <div>
    <%= form_with model: @new_category, url: categories_path do |f| %>
      <div>
        <div>
          <%= f.label :name, "Category Name", class: 'form-label' %><br><br>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true %>
        </div>
        <br>
        <div>
          <%= f.label :icon, "Category Icon", class: 'form-label' %>
          <%= f.file_field :icon, autocomplete: "icon", class: 'form-control', required: true %>
        </div>
        <div class="footer">
          <%= f.submit "SAVE", class: 'save-btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/expenses/index.html.erb
<nav>
  <%= link_to "/categories" do %>
    <i class="material-icons md-36">arrow_back</i>
  <% end %>
  <h2>TRANSACTIONS</h2>
  <i class="material-icons md-36">search</i>
</nav>

<div class="container">
  <%= render 'shared/notification_box' %>

  <div>
    <div class='category-item category-item-row'>
      <div class="img-container">
        <%= image_tag(@category.icon_url) if @category.icon %>
      </div>

      <div class="name-date-col">
        <h3><%= @category.name %></h3>
        <p><%= @category.format_date(@category.created_at) %></p>
      </div>
    </div>

    <h3>
      <h3>Total: $<%= number_with_delimiter(@expenses_sum, delimiter: ',') + "0" %></h3>
    </h3>
  </div>

  <div class='item'>
    <% if @expenses.empty? %>
      <p>No items available.</p>
    <% else %>
      <% @expenses.each_with_index do |t, i| %>
        <hr>
        <div class="expense-container">
          <div>
            <h3><%= t.name %><br>
            <small><%= t.format_date(t.created_at) %></small></h3>
          </div>

          <div class="amount-col">
            <h4>Amount<br>
            <small><%= "$" + number_with_delimiter(t.amount, delimiter: ',') + "0" %></small></h4>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="footer">
    <%= link_to "ADD TRANSACTION", new_category_expense_path(@category), class: "add-trans-btn", role: "button" %>
  </div>
</div>

app/views/expenses/new.html.erb
<nav>
  <%= link_to category_expenses_path(@category.id) do %>
    <i class="material-icons md-36">arrow_back</i>
  <% end %>
  <h2>ADD TRANSACTION</h2>
  <i class="material-icons md-36">search</i>
</nav>

<div class="container">
  <%= render 'shared/notification_box' %>

  <%= form_with model: @new_expense, url: category_expenses_path do |f| %>
    <div>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true, placeholder: "Transaction Name" %>
    </div>

    <div>
      <%= f.number_field :amount, autocomplete: "amount", class: 'form-control', required: true, step: "0.01", placeholder: "Amount" %>
    </div>

    <div class="footer">
      <%= f.submit "SAVE", class: 'save-btn' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<section class="home-container">

  <div class="logo-container">
    <%= image_tag "logo.png", alt: "App Logo", style: "width: 150px;" %>
  </div>

  <div class="large-button">
    <%= link_to "LOG IN", new_user_session_path, class: "login-btn", role: "button" %>
    <%= link_to "SIGN UP", new_user_registration_path, class: "signup-btn", role: "button" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Money Matters</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="http://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_notification_box.html.erb
    <div>
      <% if alert %>
        <div>
          <%= alert %>
        </div>
      <% end %>

      <% if notice %>
        <div>
          <%= notice %>
        </div>
      <% end %>
    </div>